spring:
  application:
    name: easybuild
  profiles:
    active: dev
server:
  servlet:
    context-path: /easybuild
  port: 8080

easy:
  swagger:
    enable: true
    profile: test
  context:
    debug: false
    pretty: false


