spring:
  application:
    name: easybuild
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/panther_dev?useUnicode=true&characterEncoding=UTF-8
    # Jasypt加密 可到common包中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    # java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="dbpassword" password=encodepassword algorithm=PBEWithMD5AndDES
    username: ENC(S2G86yhb0OMJMeNXUaGwYw==)
    password: ENC(GfP4qfnrJeqMvzN1nOemIQ==)

server:
  servlet:
    context-path: /easybuild
  port: 8080

easy:
  swagger:
    enable: true
    profile: test
  context:
    debug: true
    pretty: false
  dup: # 是否启用 防请求重复提交 支持两种方式
    open: true
  lock: # 是否注册分布式锁 SingleRedisDistributeLock
    open: true
    timeout: 5000 # 获取锁超时时间
    expireTime: 10000 #失效时间
  redis:
    host: localhost
    port: 6379
    maxTotal:
    maxIdle:
    minIdle:
  http:
    connect-timeout: 30000
    connection-request-timeout: 30000
    socket-timeout: 60000
    max-total: 200
    default-max-per-route: 200
  cors:
    enable: true
    allowOrigin: localhost:8080,local.cecloud.com:8080,chrome-extension://coohjcphdfgbiolnekdpbcijmhambjff
  security: #  请求参数加密 支持@RequestBody post方式 application/json
    encrypt-request:
      enable: true
  login:
    open: true
    path-patterns:
      - /**
    exclude-path-patterns:
      - /*/*.html
      - /*/*.js
      - /*/*.css
      - /*/*.woff
      - /*/*.ttf
    seq:
      workerId: 1
      datacenterId: 1

minbox:
  config:
    author: 恒宇少年 - 于起宇
    blog-address: http://blog.yuqiyu.com


jasypt:
  encryptor:
    password: encodepassword # 加密秘钥





