spring:
  application:
    name: easybuild
  profiles:
    active: dev
server:
  servlet:
    context-path: /easybuild
  port: 8080

easy:
  swagger:
    enable: true
    profile: test
  context:
    debug: true
    pretty: false
  dup: # 是否启用 防请求重复提交
    open: true
  lock: # 是否注册分布式锁 SingleRedisDistributeLock
    open: true
    timeout: 5000 # 获取锁超时时间
    expireTime: 10000 #失效时间
  redis:
    host: localhost
    port: 6379
    maxTotal:
    maxIdle:
    minIdle:
  http:
    connect-timeout: 30000
    connection-request-timeout: 30000
    socket-timeout: 60000
    max-total: 200
    default-max-per-route: 200
  cors:
    enable: true
    allowOrigin: www.test1.com,www.test2.com,localhost







