spring:
  application:
    name: easybuild
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/panther_dev?useUnicode=true&characterEncoding=UTF-8
    # Jasypt加密 可到common包中找到JasyptUtil加解密工具类生成加密结果 格式为ENC(加密结果)
    # java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="dbpassword" password=encodepassword algorithm=PBEWithMD5AndDES
    username: ENC(S2G86yhb0OMJMeNXUaGwYw==)
    password: ENC(GfP4qfnrJeqMvzN1nOemIQ==)

server:
  servlet:
    context-path: /easybuild
  port: 8080

# apollo 配置中心
app:
  id: apollo-demo
apollo:
  bootstrap:
    enable: false
    namespaces: application

# easybuild 框架相关配置
easy:
  swagger:
    enable: true
    profile: test
  context:
    debug: true
    pretty: false
  dup: # 是否启用 防请求重复提交 支持两种方式
    open: false
  http:
    connect-timeout: 30000
    connection-request-timeout: 30000
    socket-timeout: 60000
    max-total: 200
    default-max-per-route: 200
  cors:
    enable: true
    allowOrigin: localhost:8080,local.cecloud.com:8080,chrome-extension://coohjcphdfgbiolnekdpbcijmhambjff
  security: #  请求参数加密 支持@RequestBody post方式 application/json
    encrypt-request:
      enable: true
  login:
    open: true
    path-patterns:
      - /**
    exclude-path-patterns:
      - /*/*.html
      - /*/*.js
      - /*/*.css
      - /*/*.woff
      - /*/*.ttf
  seq:
    workerId: 1
    datacenterId: 1
  rocketmq:
    producer:
      transaction:
        enable: true
      nameSrvAddr: localhost:9876
      group: ProducerGroup
      topic: default_topic
      tag: '*'
    consumer:
      nameSrvAddr: localhost:9876
      group: ConsumerGroup
      topic: default_topic
      tag: '*'



  redis:
    redisson:
      file: classpath:redisson.yaml
      config:
        clusterServersConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          failedSlaveReconnectionInterval: 3000
          failedSlaveCheckInterval: 60000
          password: U20WtKUOat!iibr7
          subscriptionsPerConnection: 5
          clientName: null
#          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          slaveConnectionMinimumIdleSize: 24
          slaveConnectionPoolSize: 64
          masterConnectionMinimumIdleSize: 24
          masterConnectionPoolSize: 64
          readMode: "SLAVE"
          subscriptionMode: "SLAVE"
          nodeAddresses:
          - "redis://172.24.2.164:13666"
          - "redis://172.24.2.164:13777"
          - "redis://172.24.2.164:13888"
          scanInterval: 1000
          pingConnectionInterval: 0
          keepAlive: false
          tcpNoDelay: false
        threads: 16
        nettyThreads: 32
#        codec: !<org.redisson.codec.SmileJacksonCodec> {}
        transportMode: "NIO"

# 加密
jasypt:
  encryptor:
    password: encodepassword # 加密秘钥





